### ISSUE TITLE
Thay đổi giao điện đăng nhập dễ nhìn hơn

### ISSUE THREAD

**Issue by trngngx** [vuongthanh148/LearnAboutTheShapes#12]

**Comment by vuongthanh148** [comment]
Giao diện hiện tại chưa đầy đủ và nhìn dễ bị rối mắt. Cần tìm background và thay đổi UI sao cho hợp lý hơn để phù hợp với chức năng lưu trữ thông tin đăng ký của người dùng

**Comment by trngngx** [comment]
đã hoàn thành
